package report

import (
	"fmt"
	"html"
	"regexp"
	"strings"
)

// boldInlineRE matches **inline bold** spans for substitution to <strong>.
// Mirrors Python `re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', line)`.
var boldInlineRE = regexp.MustCompile(`\*\*(.+?)\*\*`)

// RenderHTML converts a validation_summary.md (or diff/timeline) string
// into a self-contained styled HTML document. Pure stdlib — no third-party
// markdown library — to match the Python `_markdown_to_html` behavior
// exactly. The output is byte-stable; golden tests compare against fixed
// fixtures.
//
// The renderer is intentionally narrow: it handles only the headings
// (h1/h2/h3), code fences (```), unordered lists (-), bold-only lines,
// horizontal rules (---), inline bold, and blank lines that the Python
// reports actually contain. Anything else falls through as a <p>.
func RenderHTML(md, partnerName string) string {
	body := mdToBody(md)

	return fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Validation Report — %s</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 40px 20px; line-height: 1.6; color: #333; }
        h1 { color: #1a1a1a; border-bottom: 2px solid #e0e0e0; padding-bottom: 10px; }
        h2 { color: #2c3e50; margin-top: 30px; }
        h3 { margin-top: 20px; }
        pre { background: #f5f5f5; padding: 15px; border-radius: 6px; overflow-x: auto; font-size: 13px; white-space: pre-wrap; }
        li { margin: 4px 0; }
        hr { border: none; border-top: 1px solid #e0e0e0; margin: 30px 0; }
        .pass { color: #27ae60; }
        .fail { color: #e74c3c; }
        @media print { body { max-width: 100%%; padding: 20px; } }
    </style>
</head>
<body>
%s
<footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e0e0e0; color: #888; font-size: 12px;">
    Generated by Thor CLI
</footer>
</body>
</html>`, html.EscapeString(partnerName), body)
}

// mdToBody is the core line-walker. Returns the inner <body> markup
// (without surrounding <body> tags) so the template above just inlines
// it.
func mdToBody(md string) string {
	lines := strings.Split(md, "\n")
	var out strings.Builder
	inCodeBlock := false

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)

		if strings.HasPrefix(trimmed, "```") {
			if inCodeBlock {
				out.WriteString("</pre>")
				inCodeBlock = false
			} else {
				out.WriteString("<pre>")
				inCodeBlock = true
			}
			out.WriteByte('\n')
			continue
		}

		if inCodeBlock {
			// Preserve original (untrimmed) line content but escape it.
			out.WriteString(html.EscapeString(line))
			out.WriteByte('\n')
			continue
		}

		switch {
		case strings.HasPrefix(line, "### "):
			fmt.Fprintf(&out, "<h3>%s</h3>", htmlInline(line[4:]))
		case strings.HasPrefix(line, "## "):
			fmt.Fprintf(&out, "<h2>%s</h2>", htmlInline(line[3:]))
		case strings.HasPrefix(line, "# "):
			fmt.Fprintf(&out, "<h1>%s</h1>", htmlInline(line[2:]))
		case strings.HasPrefix(line, "- "):
			fmt.Fprintf(&out, "<li>%s</li>", htmlInline(line[2:]))
		case strings.HasPrefix(line, "**") && strings.HasSuffix(line, "**") && len(line) > 4:
			// Whole-line bold. Mirrors Python branch.
			fmt.Fprintf(&out, "<p><strong>%s</strong></p>", htmlInline(line[2:len(line)-2]))
		case trimmed == "---":
			out.WriteString("<hr>")
		case trimmed == "":
			// preserve blank line for diff readability
		default:
			fmt.Fprintf(&out, "<p>%s</p>", htmlInline(line))
		}

		if i < len(lines)-1 {
			out.WriteByte('\n')
		}
	}
	return out.String()
}

// htmlInline escapes the input then re-applies inline **bold** markers
// as <strong>. The order matters: escape first, then substitute the
// markers (the markdown asterisks are ASCII and aren't touched by escape).
func htmlInline(s string) string {
	escaped := html.EscapeString(s)
	return boldInlineRE.ReplaceAllString(escaped, `<strong>$1</strong>`)
}
