// Package report renders validator results as Markdown and HTML, and
// produces the diff/timeline views surfaced by `thor diff`.
package report

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"thor-golang/internal/validator"
)

// Summary is the input to RenderMarkdown. It carries the raw per-control
// results plus the metadata the report header references.
type Summary struct {
	PartnerName   string
	ApplicationID string // optional; rendered as "N/A" when empty
	Ticket        string // optional; rendered as "N/A" when empty
	Timestamp     time.Time
	Results       []validator.Result // controls in iteration order
}

// statusGroup classifies a result for the summary report:
// PASSED → "passed", WAIVED → "waived", everything else → "failed".
// Mirrors the Python `_handle_validate` accounting where ERRORED was
// implicitly bucketed with FAIL.
func statusGroup(s validator.Status) string {
	switch s {
	case validator.StatusPassed:
		return "passed"
	case validator.StatusWaived:
		return "waived"
	default:
		return "failed"
	}
}

// RenderMarkdown emits the validation_summary.md format the Python
// validator writes to <partner>/validation_summary.md and to
// <partner>/reports/summary/validation_summary_<ts>.md.
//
// The output is byte-stable for a given input — golden tests rely on it.
func RenderMarkdown(s Summary) string {
	var b strings.Builder

	stamp := s.Timestamp
	if stamp.IsZero() {
		stamp = time.Now().UTC()
	}

	total := len(s.Results)
	var passed, failed, waived int
	for _, r := range s.Results {
		switch statusGroup(r.Status) {
		case "passed":
			passed++
		case "waived":
			waived++
		default:
			failed++
		}
	}

	passRate := 0.0
	failRate := 0.0
	if total > 0 {
		passRate = float64(passed) / float64(total) * 100
		failRate = float64(failed+waived) / float64(total) * 100
	}

	fmt.Fprintf(&b, "# Validation Summary\n\n")
	fmt.Fprintf(&b, "**Partner**: %s\n", nonEmpty(s.PartnerName, "N/A"))
	fmt.Fprintf(&b, "**Application ID**: %s\n", nonEmpty(s.ApplicationID, "N/A"))
	fmt.Fprintf(&b, "**Timestamp**: %s\n", stamp.Format("2006-01-02 15:04:05"))
	fmt.Fprintf(&b, "**Ticket**: %s\n\n", nonEmpty(s.Ticket, "N/A"))

	fmt.Fprintf(&b, "## Results Overview\n")
	fmt.Fprintf(&b, "- **Total Controls**: %d\n", total)
	fmt.Fprintf(&b, "- **Passed**: %d (%.1f%%)\n", passed, passRate)
	fmt.Fprintf(&b, "- **Failed**: %d (%.1f%%)\n\n", failed+waived, failRate)

	// Group results.
	var passedRows, failedRows []validator.Result
	for _, r := range s.Results {
		if statusGroup(r.Status) == "passed" {
			passedRows = append(passedRows, r)
		} else {
			failedRows = append(failedRows, r)
		}
	}

	if len(passedRows) > 0 {
		fmt.Fprintf(&b, "## Passed Controls\n\n")
		for _, r := range passedRows {
			fmt.Fprintf(&b, "### %s\n\n", r.ControlID)
			if r.Reasoning != "" {
				fmt.Fprintf(&b, "**Reason**:\n```\n%s\n```\n\n", truncate(r.Reasoning, 1000))
			}
		}
	}

	if len(failedRows) > 0 {
		fmt.Fprintf(&b, "## Failed Controls\n\n")
		for _, r := range failedRows {
			fmt.Fprintf(&b, "### %s\n", r.ControlID)
			if r.Reasoning != "" {
				fmt.Fprintf(&b, "\n**Reason**:\n```\n%s\n```\n\n", truncate(r.Reasoning, 1000))
			}
		}
	}

	b.WriteString("---\n")
	b.WriteString("*Generated by Thor CLI*\n")
	return b.String()
}

// truncate returns s if its length is <= n, otherwise s[:n]. Mirrors the
// Python `reason[:1000]` slice — byte-based truncation is fine here since
// the Reasoning text is ASCII in practice and the report is informational.
func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n]
}

func nonEmpty(s, fallback string) string {
	if s == "" {
		return fallback
	}
	return s
}

// SortResults returns a copy of in sorted by ControlID. Convenience for
// callers who want stable ordering before rendering.
func SortResults(in []validator.Result) []validator.Result {
	out := append([]validator.Result(nil), in...)
	sort.Slice(out, func(i, j int) bool { return out[i].ControlID < out[j].ControlID })
	return out
}
