package report

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"thor-golang/internal/validator"
)

// ------------------------------------------------------------------
// RenderMarkdown — golden output, byte-stable
// ------------------------------------------------------------------

func TestRenderMarkdown_GoldenOutput(t *testing.T) {
	got := RenderMarkdown(Summary{
		PartnerName: "ExamplePartner",
		Timestamp:   time.Date(2026, 5, 13, 10, 30, 0, 0, time.UTC),
		Results: []validator.Result{
			{ControlID: "ACCT-001", Status: validator.StatusPassed, Reasoning: "All good."},
			{ControlID: "DOC-006", Status: validator.StatusWaived, Reasoning: "manual review required"},
			{ControlID: "PS-001-SOFTWARE", Status: validator.StatusFailed, Reasoning: "missing evidence"},
		},
	})

	want := `# Validation Summary

**Partner**: ExamplePartner
**Application ID**: N/A
**Timestamp**: 2026-05-13 10:30:00
**Ticket**: N/A

## Results Overview
- **Total Controls**: 3
- **Passed**: 1 (33.3%)
- **Failed**: 2 (66.7%)

## Passed Controls

### ACCT-001

**Reason**:
` + "```\nAll good.\n```\n\n" + `## Failed Controls

### DOC-006

**Reason**:
` + "```\nmanual review required\n```\n\n" + `### PS-001-SOFTWARE

**Reason**:
` + "```\nmissing evidence\n```\n\n" + `---
*Generated by Thor CLI*
`

	if got != want {
		t.Errorf("markdown drift\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestRenderMarkdown_EmptyResultsHasZeroPercent(t *testing.T) {
	got := RenderMarkdown(Summary{
		PartnerName: "Empty",
		Timestamp:   time.Date(2026, 5, 13, 10, 30, 0, 0, time.UTC),
	})
	for _, want := range []string{"Total Controls**: 0", "Passed**: 0 (0.0%)"} {
		if !strings.Contains(got, want) {
			t.Errorf("expected to find %q in:\n%s", want, got)
		}
	}
}

func TestRenderMarkdown_TruncatesLongReasoning(t *testing.T) {
	long := strings.Repeat("x", 1500)
	out := RenderMarkdown(Summary{
		PartnerName: "P",
		Timestamp:   time.Date(2026, 5, 13, 10, 30, 0, 0, time.UTC),
		Results: []validator.Result{
			{ControlID: "C", Status: validator.StatusFailed, Reasoning: long},
		},
	})
	// 1000-char cap on the reason; the surrounding ``` and headers add some
	// fixed bytes, so just check we didn't dump the whole 1500 chars.
	if strings.Contains(out, strings.Repeat("x", 1001)) {
		t.Error("reason was not truncated to 1000 chars")
	}
	if !strings.Contains(out, strings.Repeat("x", 1000)) {
		t.Error("reason was truncated to fewer than 1000 chars")
	}
}

// ------------------------------------------------------------------
// RenderHTML — round-trips through the line walker
// ------------------------------------------------------------------

func TestRenderHTML_HasSelfContainedShell(t *testing.T) {
	html := RenderHTML("# title\n\n## section\n", "ExamplePartner")
	for _, want := range []string{
		"<!DOCTYPE html>",
		`<title>Validation Report — ExamplePartner</title>`,
		"<h1>title</h1>",
		"<h2>section</h2>",
		"Generated by Thor CLI",
	} {
		if !strings.Contains(html, want) {
			t.Errorf("HTML missing %q", want)
		}
	}
}

func TestRenderHTML_EscapesUserContent(t *testing.T) {
	got := RenderHTML("# <script>alert(1)</script>\n", "Acme & Co")
	if strings.Contains(got, "<script>alert(1)</script>") {
		t.Error("user content was not HTML-escaped in body")
	}
	if strings.Contains(got, "Acme & Co<") {
		// We expect Acme &amp; Co in the title.
		t.Error("partner name was not HTML-escaped in title")
	}
	if !strings.Contains(got, "Acme &amp; Co") {
		t.Error("partner name should be escaped to Acme &amp; Co")
	}
}

func TestRenderHTML_HandlesCodeFenceAndBold(t *testing.T) {
	md := "# h\n\n**bold line**\n\nplain with **inline bold** here\n\n```\ncode <here>\n```\n"
	got := RenderHTML(md, "P")
	if !strings.Contains(got, "<p><strong>bold line</strong></p>") {
		t.Error("missing whole-line bold")
	}
	if !strings.Contains(got, "plain with <strong>inline bold</strong> here") {
		t.Error("missing inline bold substitution")
	}
	if !strings.Contains(got, "<pre>") || !strings.Contains(got, "</pre>") {
		t.Error("code fence was not wrapped in <pre>")
	}
	if !strings.Contains(got, "code &lt;here&gt;") {
		t.Error("code-block contents must be HTML-escaped")
	}
}

func TestRenderHTML_HorizontalRule(t *testing.T) {
	got := RenderHTML("a\n\n---\n\nb\n", "P")
	if !strings.Contains(got, "<hr>") {
		t.Error("missing <hr>")
	}
}

// ------------------------------------------------------------------
// ParseSummary + RenderDiff
// ------------------------------------------------------------------

func writeReport(t *testing.T, dir, ts string, results []validator.Result) string {
	t.Helper()
	path := filepath.Join(dir, "validation_summary_"+ts+".md")
	body := RenderMarkdown(Summary{
		PartnerName: "P",
		Timestamp:   time.Date(2026, 5, 13, 10, 30, 0, 0, time.UTC),
		Results:     results,
	})
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestParseSummary_RoundTrip(t *testing.T) {
	dir := t.TempDir()
	path := writeReport(t, dir, "20260513_103000", []validator.Result{
		{ControlID: "ACCT-001", Status: validator.StatusPassed, Reasoning: "ok"},
		{ControlID: "DOC-006", Status: validator.StatusFailed, Reasoning: "missing"},
	})

	got, err := ParseSummary(path)
	if err != nil {
		t.Fatal(err)
	}
	if got["ACCT-001"].Status != "PASS" || got["ACCT-001"].Reasoning != "ok" {
		t.Errorf("ACCT-001: %+v", got["ACCT-001"])
	}
	if got["DOC-006"].Status != "FAIL" || got["DOC-006"].Reasoning != "missing" {
		t.Errorf("DOC-006: %+v", got["DOC-006"])
	}
}

func TestRenderDiff_StatusChangeHighlighted(t *testing.T) {
	r1 := map[string]ParsedResult{
		"ACCT-001": {Status: "PASS", Reasoning: "good v1"},
		"DOC-006":  {Status: "FAIL", Reasoning: "missing v1"},
	}
	r2 := map[string]ParsedResult{
		"ACCT-001": {Status: "PASS", Reasoning: "good v2"},
		"DOC-006":  {Status: "PASS", Reasoning: "fixed it"},
	}
	got := RenderDiff("Acme", "20260101", "20260102", r1, r2)

	for _, want := range []string{
		"# Validation Diff — Acme",
		"`20260101` (2 controls) → `20260102` (2 controls)",
		"**Changed:** 1 | **Unchanged Pass:** 1 | **Unchanged Fail:** 0",
		"### DOC-006: FAIL → PASS",
		"**Previous reasoning:** missing v1",
		"**Current reasoning:** fixed it",
		"## Still Passing (1 controls)",
		"ACCT-001",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("diff missing %q\n%s", want, got)
		}
	}
}

func TestRenderDiff_NewAndRemovedControls(t *testing.T) {
	r1 := map[string]ParsedResult{
		"GONE-001": {Status: "PASS"},
	}
	r2 := map[string]ParsedResult{
		"NEW-001": {Status: "FAIL"},
	}
	got := RenderDiff("Acme", "ts1", "ts2", r1, r2)
	if !strings.Contains(got, "## New in latest run (1 controls)") {
		t.Error("missing new-section heading")
	}
	if !strings.Contains(got, "- NEW-001: FAIL") {
		t.Error("missing NEW-001 row")
	}
	if !strings.Contains(got, "## Not in latest run (1 controls)") {
		t.Error("missing removed-section heading")
	}
	if !strings.Contains(got, "- GONE-001 (was PASS)") {
		t.Error("missing removed row")
	}
}

// ------------------------------------------------------------------
// ListReports + RenderTimeline
// ------------------------------------------------------------------

func TestListReports_OrdersChronologically(t *testing.T) {
	dir := t.TempDir()
	summaryDir := filepath.Join(dir, "reports", "summary")
	if err := os.MkdirAll(summaryDir, 0o750); err != nil {
		t.Fatal(err)
	}
	for _, ts := range []string{"20260102_100000", "20260101_080000", "20260103_140000"} {
		writeReport(t, summaryDir, ts, []validator.Result{{ControlID: "X", Status: validator.StatusPassed}})
	}
	got, err := ListReports(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 3 {
		t.Fatalf("got %d reports, want 3", len(got))
	}
	want := []string{"20260101_080000", "20260102_100000", "20260103_140000"}
	for i, r := range got {
		if r.Timestamp != want[i] {
			t.Errorf("[%d] = %s, want %s", i, r.Timestamp, want[i])
		}
	}
}

func TestListReports_MissingDirReturnsActionableError(t *testing.T) {
	dir := t.TempDir()
	_, err := ListReports(dir)
	if err == nil {
		t.Fatal("want error for missing reports/summary/")
	}
	if !strings.Contains(err.Error(), "run validation") {
		t.Errorf("error should be actionable; got %q", err.Error())
	}
}

func TestRenderTimeline_TableShape(t *testing.T) {
	dir := t.TempDir()
	summaryDir := filepath.Join(dir, "reports", "summary")
	if err := os.MkdirAll(summaryDir, 0o750); err != nil {
		t.Fatal(err)
	}
	writeReport(t, summaryDir, "20260101_080000", []validator.Result{
		{ControlID: "ACCT-001", Status: validator.StatusPassed, Reasoning: "ok"},
		{ControlID: "DOC-001", Status: validator.StatusFailed, Reasoning: "no"},
	})
	writeReport(t, summaryDir, "20260102_090000", []validator.Result{
		{ControlID: "ACCT-001", Status: validator.StatusPassed, Reasoning: "ok"},
		{ControlID: "DOC-001", Status: validator.StatusPassed, Reasoning: "fixed"},
	})

	reports, err := ListReports(dir)
	if err != nil {
		t.Fatal(err)
	}
	got, err := RenderTimeline("Acme", reports)
	if err != nil {
		t.Fatal(err)
	}

	for _, want := range []string{
		"# Validation Timeline — Acme",
		"| Run | Date | Controls | Passed | Failed | Pass Rate |",
		"| #1 | 2026-01-01 08:00 | 2 | 1 | 1 | 50% |",
		"| #2 | 2026-01-02 09:00 | 2 | 2 | 0 | 100% |",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("timeline missing %q\n%s", want, got)
		}
	}
}

func TestFindReport_FuzzyMatch(t *testing.T) {
	reports := []ReportFile{
		{Path: "/x/validation_summary_20260101_080000.md", Timestamp: "20260101_080000"},
		{Path: "/x/validation_summary_20260102_090000.md", Timestamp: "20260102_090000"},
	}
	if r := FindReport(reports, "20260102"); r == nil || r.Timestamp != "20260102_090000" {
		t.Errorf("fuzzy match failed: %+v", r)
	}
	if r := FindReport(reports, ""); r != nil {
		t.Error("empty input must return nil")
	}
	if r := FindReport(reports, "no-such-thing"); r != nil {
		t.Error("non-matching input must return nil")
	}
}
