/**
 * thor_export — Render validation_summary.md to self-contained HTML.
 * Inlines CSS, shows pass/fail with colors, shareable as a single file.
 */

import { readFileSync, writeFileSync, existsSync } from "fs";
import { join, dirname } from "path";

/**
 * Convert markdown summary to styled HTML.
 */
function markdownToHtml(md) {
  let html = md;

  // Escape HTML entities in code blocks first
  html = html.replace(/```\n?([\s\S]*?)```/g, (_, code) => {
    const escaped = code.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    return `<pre><code>${escaped}</code></pre>`;
  });

  // Headers
  html = html.replace(/^### (.+)$/gm, "<h3>$1</h3>");
  html = html.replace(/^## (.+)$/gm, "<h2>$1</h2>");
  html = html.replace(/^# (.+)$/gm, "<h1>$1</h1>");

  // Bold
  html = html.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");

  // List items
  html = html.replace(/^- (.+)$/gm, "<li>$1</li>");
  html = html.replace(/(<li>.*<\/li>\n?)+/g, (match) => `<ul>${match}</ul>`);

  // Horizontal rules
  html = html.replace(/^---$/gm, "<hr>");

  // Paragraphs (lines not already wrapped)
  html = html.replace(/^(?!<[huplo]|<\/|<hr|<pre)(.+)$/gm, "<p>$1</p>");

  // Newlines
  html = html.replace(/\n\n+/g, "\n");

  return html;
}

/**
 * Inject pass/fail coloring into control sections.
 */
function colorizeControls(html) {
  // Color passed controls green
  html = html.replace(
    /(<h2>Passed Controls<\/h2>)([\s\S]*?)(?=<h2>|<hr|$)/g,
    (_, header, content) => `${header}<div class="passed-section">${content}</div>`
  );

  // Color failed controls red
  html = html.replace(
    /(<h2>Failed Controls<\/h2>)([\s\S]*?)(?=<h2>|<hr|$)/g,
    (_, header, content) => `${header}<div class="failed-section">${content}</div>`
  );

  // Color waived controls amber
  html = html.replace(
    /(<h2>Waived Controls<\/h2>)([\s\S]*?)(?=<h2>|<hr|$)/g,
    (_, header, content) => `${header}<div class="waived-section">${content}</div>`
  );

  return html;
}

const CSS = `
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    line-height: 1.6;
    color: #1a1a2e;
    background: #f8f9fa;
    padding: 2rem;
    max-width: 900px;
    margin: 0 auto;
  }
  h1 { color: #1a1a2e; margin: 1rem 0; border-bottom: 3px solid #232f3e; padding-bottom: 0.5rem; }
  h2 { color: #232f3e; margin: 1.5rem 0 0.5rem; }
  h3 { margin: 1rem 0 0.3rem; padding: 0.3rem 0.6rem; border-radius: 4px; }
  p, li { margin: 0.3rem 0; }
  ul { padding-left: 1.5rem; }
  pre {
    background: #f1f3f5;
    border: 1px solid #dee2e6;
    border-radius: 6px;
    padding: 0.8rem;
    overflow-x: auto;
    font-size: 0.85rem;
    margin: 0.5rem 0;
  }
  code { font-family: 'SF Mono', Monaco, 'Cascadia Code', monospace; }
  hr { border: none; border-top: 1px solid #dee2e6; margin: 2rem 0; }
  strong { color: #232f3e; }

  .passed-section h3 {
    background: #d4edda;
    border-left: 4px solid #28a745;
    color: #155724;
  }
  .failed-section h3 {
    background: #f8d7da;
    border-left: 4px solid #dc3545;
    color: #721c24;
  }
  .waived-section h3 {
    background: #fff3cd;
    border-left: 4px solid #ffc107;
    color: #856404;
  }

  .summary-badge {
    display: inline-block;
    padding: 0.2rem 0.6rem;
    border-radius: 12px;
    font-weight: bold;
    font-size: 0.85rem;
    margin-right: 0.5rem;
  }
  .badge-pass { background: #28a745; color: white; }
  .badge-fail { background: #dc3545; color: white; }
  .badge-waive { background: #ffc107; color: #333; }

  @media print {
    body { padding: 1rem; }
    pre { white-space: pre-wrap; }
  }
</style>
`;

/**
 * Export validation summary to HTML.
 */
export function exportHtml(partnerFolder, outputPath) {
  const summaryPath = join(partnerFolder, "validation_summary.md");

  if (!existsSync(summaryPath)) {
    throw new Error(`No validation_summary.md found in ${partnerFolder}. Run thor_validate first.`);
  }

  const md = readFileSync(summaryPath, "utf-8");
  let bodyHtml = markdownToHtml(md);
  bodyHtml = colorizeControls(bodyHtml);

  const fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Thor PSA Validation Report</title>
  ${CSS}
</head>
<body>
  ${bodyHtml}
  <footer style="margin-top:2rem;padding-top:1rem;border-top:1px solid #dee2e6;color:#6c757d;font-size:0.8rem;">
    Generated by Thor PSA Validator &mdash; ${new Date().toISOString()}
  </footer>
</body>
</html>`;

  const outPath = outputPath || join(partnerFolder, "validation_report.html");
  writeFileSync(outPath, fullHtml, "utf-8");

  return `Exported HTML report to: ${outPath}`;
}
